event.sourcing.domain-persistence:
  events-per-snapshot: 3

management:
  endpoints:
    web:
      exposure:
        include: health

server:
  port: 8081

spring:
  cassandra:
    local-datacenter: datacenter1
    port: 9042
    contact-points: ${CASSANDRA_DB:127.0.0.1}
    keyspace-name: reservation_keyspace
  data:
    redis:
      host: ${REDIS_DB:localhost}
      port: 6379
      database: 0

adapter:
  kafka:
    bootstrap:
      servers: ${BROKERS:localhost:9092}

    consumer:
      group-id: reservation-service

    topics:
      customer-event-customer-document: customer.event.customer-document
      reservation-system-event-reservation-document: reservation-system.event.reservation-document
      reservation-system-event-time-slot-document: reservation-system.event.time-slot-document