event.sourcing.domain-persistence:
  events-per-snapshot: 3

spring:
  redis:
    host: localhost
    port: 6379
    database: 0

  data:
    cassandra:
      local-datacenter: datacenter1
      keyspace-name: customer_keyspace
      contact-points: 127.0.0.1
      port: 9042
