event.sourcing.domain-persistence:
  events-per-snapshot: 3

server:
  port: 8082

adapter:
  kafka:
    bootstrap:
      servers: ${BROKERS:localhost:9092}

    consumer:
      group-id: customer-service

    topics:
      customer-event-customer-document: customer.event.customer-document

spring:
  cassandra:
    local-datacenter: datacenter1
    port: 9042
    contact-points: 127.0.0.1
    keyspace-name: customer_keyspace
  data:
    redis:
      host: localhost
      port: 6379
      database: 0
