version: '3.9'
services:
  redis-db:
    image: redis:7.2.1
    ports:
      - 6379:6379
    volumes:
      - redis-db-data:/data
    networks:
      - reservation-system
  cassandra-db-init-liquibase-keyspace:
    image: cassandra:4.1.3
    volumes:
      - ./src/main/Docker/liquibase/Cassandra/init/create-liquibase-keyspace.cql:/create-liquibase-keyspace.cql
      - ./src/main/Docker/liquibase/Cassandra/init/init-db.sh:/init-db.sh
    networks:
      - reservation-system
    depends_on:
      cassandra-db:
        condition: service_healthy
    command: /bin/bash -c "echo loading cassandra keyspace && cqlsh cassandra-db -f /create-liquibase-keyspace.cql"

  cassandra-db:
    build:
      context: ./src/main/Docker/Cassandra
    ports:
      - 9042:9042
    volumes:
      - cassandra-db-data:/var/lib/cassandra
    networks:
      - reservation-system
    healthcheck:
      test: [ "CMD-SHELL", "cqlsh --execute \"DESC KEYSPACES;\"" ]
      interval: 10s
      timeout: 10s
      retries: 10

  cassandra-liquibase-ddd-testing:
    build:
      context: ./src/main/Docker/liquibase/Cassandra
    volumes:
      - ./@ddd/event-storage-adapter-cassandra-db/build/cassandra-db/liquibase/changelog:/liquibase/changelog
    environment:
      - URL=jdbc:cassandra://cassandra-db:9042/liquibase_keyspace;DefaultKeyspace=liquibase_keyspace
      - CHANGELOG_FILE=event-sourcing-changelog.xml
      - USERNAME=cassandra
      - PASSWORD=cassandra
      - DRIVER=com.simba.cassandra.jdbc42.Driver
      - DEFAULT_SCHEMA_NAME=ddd_testing_keyspace
    depends_on:
      - cassandra-db-init-liquibase-keyspace

    #    command:
    #      - --url=jdbc:cassandra://cassandra-db:9042/liquibase_keyspace;DefaultKeyspace=liquibase_keyspace
    #      - --changeLogFile=event-sourcing-changelog.xml
    #      - --username=cassandra
    #      - --password=cassandra
    #      - --driver=com.simba.cassandra.jdbc42.Driver
    #      - --defaultSchemaName=ddd_testing_keyspace
    #      - update
    networks:
      - reservation-system

  cassandra-liquibase-customer:
    build:
      context: ./src/main/Docker/liquibase/Cassandra
    volumes:
      - ./@customer/build/cassandra-db/liquibase/changelog:/liquibase/changelog
    environment:
      - URL=jdbc:cassandra://cassandra-db:9042/liquibase_keyspace;DefaultKeyspace=liquibase_keyspace
      - CHANGELOG_FILE=customer-changelog.xml
      - USERNAME=cassandra
      - PASSWORD=cassandra
      - DRIVER=com.simba.cassandra.jdbc42.Driver
      - DEFAULT_SCHEMA_NAME=ddd_testing_keyspace
    depends_on:
      - cassandra-db-init-liquibase-keyspace

    #    command:
    #      - --url=jdbc:cassandra://cassandra-db:9042/liquibase_keyspace;DefaultKeyspace=liquibase_keyspace
    #      - --changeLogFile=customer-changelog.xml
    #      - --username=cassandra
    #      - --password=cassandra
    #      - --driver=com.simba.cassandra.jdbc42.Driver
    #      - --defaultSchemaName=ddd_testing_keyspace
    #      - update
    networks:
      - reservation-system


volumes:
  cassandra-db-data:
  redis-db-data:

networks:
  reservation-system: