services:
  ai-agent-service:
    image: ai-agent-application:0.0.1-SNAPSHOT
    ports:
      - "8083:8083"
    environment:
      BROKERS: kafka:29092
      CASSANDRA_DB: cassandra-db
      REDIS_DB: redis-db
    depends_on:
      - kafka
      - redis-db
      - cassandra-liquibase-ai-agent
    networks:
      - reservation-system
    profiles:
      - ai

  reservation-service:
    image: reservation-application:0.0.1-SNAPSHOT
    ports:
      - "8081:8081"
    environment:
      BROKERS: kafka:29092
      CASSANDRA_DB: cassandra-db
      REDIS_DB: redis-db
    depends_on:
      - kafka
      - redis-db
      - cassandra-liquibase-reservation
    networks:
      - reservation-system
    profiles:
      - system-checks
      - ai

  customer-service:
    image: customer-application:0.0.1-SNAPSHOT
    ports:
      - "8082:8082"
    environment:
      BROKERS: kafka:29092
      CASSANDRA_DB: cassandra-db
      REDIS_DB: redis-db
    depends_on:
      - kafka
      - redis-db
      - cassandra-liquibase-customer
    networks:
      - reservation-system
    profiles:
      - system-checks
      - ai

  kafka-init:
    image: confluentinc/cp-kafka:7.5.3
    volumes:
      - ./src/main/Docker/kafka/create-kafka-topics.sh:/create-kafka-topics.sh
    command: /bin/bash -c "chmod +x /create-kafka-topics.sh && /create-kafka-topics.sh"
    depends_on:
      - kafka
    networks:
      - reservation-system

  kafka:
    image: confluentinc/cp-kafka:7.5.3
    ports:
      - "9101:9101"
      - "9092:9092"
      - "29092:29092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_JMX_PORT: 9101
      KAFKA_JMX_HOSTNAME: localhost
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:29093
      KAFKA_LISTENERS: PLAINTEXT://kafka:29092,CONTROLLER://kafka:29093,PLAINTEXT_HOST://0.0.0.0:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      CLUSTER_ID: MkU3OEVBNTcwNTJENDM2Qk
    networks:
      - reservation-system
    depends_on:
      cassandra-db:
        condition: service_healthy

  control-center:
    image: confluentinc/confluent-local:7.5.3
    ports:
      - "9021:9021"
    environment:
      CONNECT_BOOTSTRAP_SERVERS: kafka:29092
      CONNECT_REST_ADVERTISED_HOST_NAME: kafka-connect
      CONNECT_GROUP_ID: compose-connect-group
      CONNECT_CONFIG_STORAGE_TOPIC: docker-connect-configs
      CONNECT_OFFSET_STORAGE_TOPIC: docker-connect-offsets
      CONNECT_STATUS_STORAGE_TOPIC: docker-connect-status
      CONNECT_KEY_CONVERTER: org.apache.kafka.connect.storage.StringConverter
      CONNECT_VALUE_CONVERTER: org.apache.kafka.connect.json.JsonConverter
      CONNECT_INTERNAL_KEY_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
      CONNECT_INTERNAL_VALUE_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
      CONNECT_REST_PORT: 8083
      CONNECT_LOG4J_ROOT_LOGLEVEL: "INFO"
      CLUSTER_ID: MkU3OEVBNTcwNTJENDM2Qk
    depends_on:
      - kafka
    networks:
      - reservation-system

  redis-db:
    image: redis:7.2.1
    ports:
      - "6379:6379"
    volumes:
      - redis-db-data:/data
    networks:
      - reservation-system
    depends_on:
      cassandra-db:
        condition: service_healthy

  cassandra-db-init-liquibase-keyspace:
    image: cassandra:4.1.3
    volumes:
      - ./src/main/Docker/liquibase/Cassandra/init/create-liquibase-keyspace.cql:/create-liquibase-keyspace.cql
      - ./src/main/Docker/liquibase/Cassandra/init/init-db.sh:/init-db.sh
    networks:
      - reservation-system
    depends_on:
      cassandra-db:
        condition: service_healthy
    command: /bin/bash -c "echo loading cassandra keyspace && cqlsh cassandra-db -f /create-liquibase-keyspace.cql"

  cassandra-db:
    build:
      context: ./src/main/Docker/Cassandra
    ports:
      - "9042:9042"
    volumes:
      - cassandra-db-data:/var/lib/cassandra
    networks:
      - reservation-system
    healthcheck:
      test: [ "CMD-SHELL", "cqlsh --execute \"DESC KEYSPACES;\"" ]
      interval: 10s
      timeout: 10s
      retries: 10

  cassandra-liquibase-ai-agent:
    build:
      context: ./src/main/Docker/liquibase/Cassandra
    container_name: reservation-system-liquibase-ai-agent
    volumes:
      - ./ai-agent/build/cassandra-db/liquibase/changelog:/liquibase/changelog
    environment:
      - URL=jdbc:cassandra://cassandra-db:9042/liquibase_keyspace;DefaultKeyspace=liquibase_keyspace
      - CHANGELOG_FILE=ai-agent-changelog.xml
      - USERNAME=cassandra
      - PASSWORD=cassandra
      - DRIVER=com.simba.cassandra.jdbc42.Driver
      - DEFAULT_SCHEMA_NAME=ai_agent_keyspace
    depends_on:
      - cassandra-db-init-liquibase-keyspace
    networks:
      - reservation-system
    healthcheck:
      test: [ "CMD-SHELL", "cqlsh cassandra-db 9042 --execute \"DESC KEYSPACE ai_agent_keyspace;\"" ]
      interval: 10s
      timeout: 10s
      retries: 10

  cassandra-liquibase-ddd-testing:
    build:
      context: ./src/main/Docker/liquibase/Cassandra
    container_name: reservation-system-liquibase-ddd-testing
    volumes:
      - ./@ddd/event-storage-adapter-cassandra-db/build/cassandra-db/liquibase/changelog:/liquibase/changelog
    environment:
      - URL=jdbc:cassandra://cassandra-db:9042/liquibase_keyspace;DefaultKeyspace=liquibase_keyspace
      - CHANGELOG_FILE=event-sourcing-changelog.xml
      - USERNAME=cassandra
      - PASSWORD=cassandra
      - DRIVER=com.simba.cassandra.jdbc42.Driver
      - DEFAULT_SCHEMA_NAME=ddd_testing_keyspace
    depends_on:
      - cassandra-db-init-liquibase-keyspace
      - cassandra-liquibase-ai-agent
    networks:
      - reservation-system
    healthcheck:
      test: [ "CMD-SHELL", "cqlsh cassandra-db 9042 --execute \"DESC KEYSPACE ddd_testing_keyspace;\"" ]
      interval: 10s
      timeout: 10s
      retries: 10

  cassandra-liquibase-customer:
    build:
      context: ./src/main/Docker/liquibase/Cassandra
    container_name: reservation-system-liquibase-customer
    volumes:
      - ./customer/build/cassandra-db/liquibase/changelog:/liquibase/changelog
    environment:
      - URL=jdbc:cassandra://cassandra-db:9042/liquibase_keyspace;DefaultKeyspace=liquibase_keyspace
      - CHANGELOG_FILE=customer-changelog.xml
      - USERNAME=cassandra
      - PASSWORD=cassandra
      - DRIVER=com.simba.cassandra.jdbc42.Driver
      - DEFAULT_SCHEMA_NAME=customer_keyspace
    depends_on:
      - cassandra-db-init-liquibase-keyspace
      - cassandra-liquibase-ddd-testing
    networks:
      - reservation-system
    healthcheck:
      test: [ "CMD-SHELL", "cqlsh cassandra-db 9042 --execute \"DESC KEYSPACE customer_keyspace;\"" ]
      interval: 10s
      timeout: 10s
      retries: 10

  cassandra-liquibase-reservation:
    build:
      context: ./src/main/Docker/liquibase/Cassandra
    container_name: reservation-system-liquibase-reservation
    volumes:
      - ./reservation/build/cassandra-db/liquibase/changelog:/liquibase/changelog
    environment:
      - URL=jdbc:cassandra://cassandra-db:9042/liquibase_keyspace;DefaultKeyspace=liquibase_keyspace
      - CHANGELOG_FILE=reservation-changelog.xml
      - USERNAME=cassandra
      - PASSWORD=cassandra
      - DRIVER=com.simba.cassandra.jdbc42.Driver
      - DEFAULT_SCHEMA_NAME=reservation_keyspace
    depends_on:
      - cassandra-db-init-liquibase-keyspace
      - cassandra-liquibase-customer
    networks:
      - reservation-system
    healthcheck:
      test: [ "CMD-SHELL", "cqlsh cassandra-db 9042 --execute \"DESC KEYSPACE reservation_keyspace;\"" ]
      interval: 10s
      timeout: 10s
      retries: 10


volumes:
  cassandra-db-data:
  redis-db-data:

networks:
  reservation-system: