spring:
  cloud:
    gateway:
      routes:
        - id: customer_service_route
          uri: http://localhost:8082/customers
          predicates:
              - Path=/customers/**
        - id: reservation_service_route
          uri: http://localhost:8081/reservation-system
          predicates:
              - Path=/reservation-system/**
        - id: ai_agent_route
          uri: http://localhost:8083/ai-agent
          predicates:
              - Path=/ai-agent/**
        - id: ollama_chat_route
          uri: http://localhost:11434/api/chat
          predicates:
            - Path=/api/chat/completions
          filters:
            - RewritePath=/api/chat/completions, /api/chat
