adapter:
  llm:
    chat:
      base-url: http://localhost:11434
      temperature: 0.2
      model: llama3-groq-tool-use
#      model: qwen2.5
#      model: llama3.2
#      model: llama3.2:1b
#      model: mistral
