server:
  port: 8083

spring:
  cassandra:
    local-datacenter: datacenter1
    port: 9042
    contact-points: ${CASSANDRA_DB:127.0.0.1}
    keyspace-name: ai_agent_keyspace
  data:
    redis:
      host: ${REDIS_DB:localhost}
      port: 6379
      database: 0

# Application specific properties
event.sourcing.domain-persistence:
  events-per-snapshot: 3

management:
  endpoints:
    web:
      exposure:
        include: health