adapter:
  llm:
    chat:
      base-url: http://localhost:11434
      temperature: 0.3
#      model: llama3-groq-tool-use
#      model: qwen3:14b
#      model: qwen2.5:1.5b
      model: qwen3:latest
#      model: qwen3:4b
#      model: qwen3:1.7b
#      model: qwen2.5-coder:1.5b
#      model: qwen2.5:latest
#      model: llama3.2
#      model: llama3.2:1b
#      model: mistral:v0.3
